-- Medix Uniformes — pagos Wompi
-- ⚠️  Este archivo fue reemplazado por phase1-payments.sql
--
-- Instalación nueva (orden):
--   1. schema.sql
--   2. seed.sql
--   3. storage.sql
--   4. payments.sql
--   5. phase1-payments.sql   ← funciones Wompi, envío, webhook y stock
--
-- Proyecto existente con wompi-rpc.sql antiguo:
--   Ejecuta solo phase1-payments.sql (actualiza funciones y columnas)
